name: Nix build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flake:
    name: Build the default package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Use cachix
        uses: cachix/cachix-action@v10
        with:
          name: quantified-uncertainty
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: nix build
        run: nix build
